### ISSUE TITLE
CloudFormationCreate buttons don't work

### ISSUE THREAD

**Issue by prashant182** [aws-samples/ecs-service-connect-yelb-sample-app#10]
## Context
When clicking on the cloudformation create button, it doesn't work properly. 

We get this error 
```
S3 error: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

```

**Comment by ollypom** [comment]
Thank you for raising this. Cloudformation create buttons have now been removed in this PR: https://github.com/aws-samples/ecs-service-connect-yelb-sample-app/pull/11
